version: "2"
services:
  eureka:
    build: ./eureka-server
    network_mode: host
    restart: always
  gateway:
    build: ./spring-boot-zuulgatewayproxy
    network_mode: host
    restart: always
  track:
    build: ./track-service
    network_mode: host
    restart: always
  user:
    build: ./user-service
    network_mode: host
    restart: always
  config:
    build: ./spring-config-server
    network_mode: host
    restart: always
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    network_mode: host
  #    volumes:
  #      - $HOME/mongo/db:/data/db
  mysql:
    image: mysql:5.7
    volumes:
      - ./dbcreation.sql:/tmp/dbcreation.sql
      - ./import.sh:/tmp/import.sh
    ports:
      - "8888:8888"
    network_mode: host
    environment:
      MYSQL_DATABASE: "mysql"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "Root@123"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"